[build]
command = "npm run build"
publish = ".next"

[build.environment]
NETLIFY_NEXT_SKEW_PROTECTION = "true"

[functions]
included_files = ["node_modules/@sparticuz/chromium/bin/**"]

[[plugins]]
package = "@netlify/plugin-nextjs"
